[project]
name = "elai"
revision = "1.0"

[[providers]]
type = "keyring"
uri = "keyring://"

[profiles.default]
ANTHROPIC_API_KEY = { description = "API Key for Anthropic", required = false }
LOG_LEVEL = { description = "Logging level", required = false, default = "debug" }
